# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the docker-env branch
  # and changes in Makefile, src and tests
  push:
    branches:
      - docker-env
    paths:
      - Makefile
      - src/**
      - tests/**
  pull_request:
    branches:
      - docker-env
    paths:
      - Makefile
      - src/**
      - tests/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/mandyoc.Dockerfile
          tags: mandyoc:latest
          outputs: type=docker,dest=/tmp/mandyoc.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mandyoc
          path: /tmp/mandyoc.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: mandyoc
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/mandyoc.tar
          docker run --rm -it mandyoc:latest bash -c 'make test'
