# This is a basic workflow to help you get started with Actions

name: Test2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the docker-env branch
  # and changes in Makefile, src and tests
  push:
    branches:
      - docker-env
    paths:
      - Makefile
      - src/**
      - tests/**
  pull_request:
    branches:
      - docker-env
    paths:
      - Makefile
      - src/**
      - tests/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build the docker image and run tests
  test:
    runs-on: ubuntu-latest

    steps:
      # Cache layer
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Need to fetch more than the last commit so that setuptools-scm can
          # create the correct version string. If the number of commits since
          # the last release is greater than this, the version still be wrong.
          # Increase if necessary.
          fetch-depth: 100
          # The GitHub token is preserved by default but this job doesn't need
          # to be able to push to GitHub.
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/mandyoc.Dockerfile
          tags: mandyoc:latest

      - name: Run tests
        run: |
          docker run --rm mandyoc:latest bash -c 'make test'
